### ISSUE TITLE
when import recurrent-js on node.js, pack to APK display minifier-js parse error.

### ISSUE THREAD

**Issue by carrot93** [mvrahden/recurrent-js#1]
import {Net,Graph} from 'recurrent-js'

..../minifier-js/node_modules/uglify-js/lib/parse.js:196:18:
Unexpected token: name (Graph)
at new JS_Parse_Error

Did that need CommonJS or TypeScript translator module?

**Comment by mvrahden** [comment]
Hey @carrot93,
sorry for the late response, I was handicapped the last month.
First question: Is this issue still current or could you solve it?
In either cases: can you please explain your issue a bit more verbose? 

- If you could solve it, can you then also please explain your solution, so that I can mark it as solved?
- If you couldn't solve it, let's then find the problem and a solution together.

Cheers

**Comment by mvrahden** [comment]
Since there hasn't been any activity regarding this request, I see this issue now as closed.
